# FROM node:24

# WORKDIR /app

# COPY package*.json ./
# RUN npm install

# COPY . .

# RUN chmod +x compile.sh

# CMD ["sh", "./compile.sh"]


FROM node:24

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ARG NEXT_PUBLIC_URL
ENV NEXT_PUBLIC_URL=$NEXT_PUBLIC_URL

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]